development:
    core:
        hostname: localhost
        port: 3000
        protocol: http://

test:
    core:
        hostname: localhost
        port: 3000
        protocol: http://

testserver:
    core:
        hostname: factlink-testserver.inverselink.com
        port: 443
        protocol: https://
        htpasswd:
          username: proxyuser
          password: "f;Y5irI:Is{[,[([Hx:4-JoWP#&usx-"

vagrant:
    core:
        hostname: localhost
        port: 3000
        protocol: http://

staging:
    core:
        hostname: factlink-staging.inverselink.com
        port: 443
        protocol: https://
        htpasswd:
          username: proxyuser
          password: "f;Y5irI:Is{[,[([Hx:4-JoWP#&usx-"

production:
    core:
        hostname: factlink.com
        port: 443
        protocol: https://
        htpasswd:
          username: proxyuser
          password: "f;Y5irI:Is{[,[([Hx:4-JoWP#&usx-"
