development:
  mixpanel:
    token: "8d6864d76fbc062074506129cd298a5f"

staging:
  mixpanel:
    token: "902850bd8575082e3b459afad9a56b8a"

production:
  mixpanel:
    token: "13827a536fd32450913ccefe24b728d3"
