development:
  static:
    hostname: localhost
    port: 8000
    protocol: http://

test:
  static:
    hostname: localhost
    port: 8000
    protocol: http://

testserver:
  static:
    hostname: static-testserver.factlink.com
    port: 443
    protocol: https://

staging:
  static:
    hostname: static-staging.factlink.com
    port: 443
    protocol: https://

production:
  static:
    hostname: static-beta.factlink.com
    port: 443
    protocol: https://
